// <auto-generated />
using System;
using Locadora.WebApp.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Locadora.WebApp.Infrastructure.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.AddressModel", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("IdEndereco");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.ClienteModel", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteIdContato")
                        .HasColumnType("int");

                    b.Property<int>("ClienteIdEndereco")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdCliente");

                    b.HasIndex("ClienteIdContato")
                        .IsUnique();

                    b.HasIndex("ClienteIdEndereco")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.ContactModel", b =>
                {
                    b.Property<int>("IdContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Celular")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdContato");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.FilmeModel", b =>
                {
                    b.Property<int>("IdFilme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FilmeIdGenero")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("IdFilme");

                    b.HasIndex("FilmeIdGenero");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            IdFilme = 1,
                            DataCriacao = new DateTime(2023, 2, 4, 21, 49, 2, 792, DateTimeKind.Local).AddTicks(8406),
                            FilmeIdGenero = 1,
                            Titulo = "IT: A Coisa"
                        },
                        new
                        {
                            IdFilme = 2,
                            DataCriacao = new DateTime(2023, 2, 4, 21, 49, 2, 792, DateTimeKind.Local).AddTicks(9044),
                            FilmeIdGenero = 2,
                            Titulo = "John Wick 3: Parabellum"
                        },
                        new
                        {
                            IdFilme = 3,
                            DataCriacao = new DateTime(2023, 2, 4, 21, 49, 2, 792, DateTimeKind.Local).AddTicks(9103),
                            FilmeIdGenero = 3,
                            Titulo = "O Homem do Norte"
                        });
                });

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.GeneroModel", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdGenero");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            IdGenero = 1,
                            DataCriacao = new DateTime(2023, 2, 4, 21, 49, 2, 791, DateTimeKind.Local).AddTicks(5066),
                            Descricao = "Terror"
                        },
                        new
                        {
                            IdGenero = 2,
                            DataCriacao = new DateTime(2023, 2, 4, 21, 49, 2, 791, DateTimeKind.Local).AddTicks(5724),
                            Descricao = "Ação"
                        },
                        new
                        {
                            IdGenero = 3,
                            DataCriacao = new DateTime(2023, 2, 4, 21, 49, 2, 791, DateTimeKind.Local).AddTicks(5742),
                            Descricao = "Drama"
                        });
                });

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.LocacaoFilmes", b =>
                {
                    b.Property<int>("LocacaoId")
                        .HasColumnType("int");

                    b.Property<int>("FilmeId")
                        .HasColumnType("int");

                    b.HasKey("LocacaoId", "FilmeId");

                    b.HasIndex("FilmeId");

                    b.ToTable("LocacaoFilmes");
                });

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.LocacaoModel", b =>
                {
                    b.Property<int>("IdLocacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdLocacao");

                    b.HasIndex("ClienteIdCliente");

                    b.ToTable("Locacoes");
                });

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.UsuarioModel", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            DataCriacao = new DateTime(2023, 2, 4, 21, 49, 2, 787, DateTimeKind.Local).AddTicks(4511),
                            Login = "admin@admin.com",
                            Nome = "admin",
                            Senha = "admin"
                        });
                });

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.ClienteModel", b =>
                {
                    b.HasOne("Locadora.WebApp.Domain.Models.ContactModel", "Contato")
                        .WithOne("Cliente")
                        .HasForeignKey("Locadora.WebApp.Domain.Models.ClienteModel", "ClienteIdContato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locadora.WebApp.Domain.Models.AddressModel", "Endereco")
                        .WithOne("Cliente")
                        .HasForeignKey("Locadora.WebApp.Domain.Models.ClienteModel", "ClienteIdEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.FilmeModel", b =>
                {
                    b.HasOne("Locadora.WebApp.Domain.Models.GeneroModel", "Genero")
                        .WithMany("Filmes")
                        .HasForeignKey("FilmeIdGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.LocacaoFilmes", b =>
                {
                    b.HasOne("Locadora.WebApp.Domain.Models.FilmeModel", "Filme")
                        .WithMany("LocacaoFilmes")
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locadora.WebApp.Domain.Models.LocacaoModel", "Locacao")
                        .WithMany("LocacaoFilmes")
                        .HasForeignKey("LocacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Locadora.WebApp.Domain.Models.LocacaoModel", b =>
                {
                    b.HasOne("Locadora.WebApp.Domain.Models.ClienteModel", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
